// Writes the Markdown report for the sales-platform research from stats + excluded list (numbers come from the data, not typed by hand).
const fs = require('fs');
const dir = process.argv[2];
const j = JSON.parse(fs.readFileSync(dir + '/uae_sales_platforms_2026-10-09.json', 'utf8'));
const s = j.stats;
const dups = j.excluded.filter((e) => e.kind === 'duplicate').length;
const L = [];
L.push('# تقرير بحث منصات البيع بالإمارات — 9 تشرين الأول 2026', '');
L.push('> بحث مصادر عامة فقط. لا Import، لا قاعدة بيانات، لا Merge، لا Deploy. المجهول = «غير معروف». لا أرقام عمولات ولا شروط إلا من صفحة رسمية قُرئت (مع رابطها).', '');
L.push('## الأعداد', '', '| البند | العدد |', '|---|---|');
L.push(`| جهات فُحصت (51 من ملف حسام + ${s.input_records - 51} إضافية) | ${s.input_records} |`);
L.push(`| بعد إزالة المكرر والمستبعد | ${s.kept} |`);
L.push(`| مكررات | ${dups} |`);
L.push(`| مستبعدة (ليست قناة بيع / مصدر بحث / رابط خاطئ) | ${s.excluded_total - dups} |`);
L.push(`| متحقق منها (موقع يعمل + مسار بيع/مورد رسمي موثّق) | ${s.verified} |`);
L.push(`| تحتاج مراجعة | ${s.needs_review} |`);
L.push(`| لم تستجب عند الفحص | ${s.unreachable} |`);
L.push(`| تحجب الفحص الآلي (لم يُتجاوز) | ${s.protected_not_verified} |`);
L.push(`| تسجيل بائع مباشر مؤكد من صفحة رسمية | ${s.direct_seller_registration_confirmed} (Amazon.ae، Tradeling، Begad) + noon بانتظار تأكيد يدوي |`);
L.push(`| تتطلب اتفاق مورد/توزيع (أو غير مؤكدة) | ${s.supplier_agreement_required} |`);
L.push(`| عندها رسوم من مصدر رسمي | ${s.with_official_fee_source} |`);
L.push(`| عندها شروط ترخيص من مصدر رسمي | ${s.with_license_req_source} |`);
L.push(`| عندها شروط تسجيل منتج من مصدر رسمي | ${s.with_product_reg_source} (غير معروف — موضوع منفصل: Montaji) |`, '');
L.push('## أهم النتائج', '');
L.push("- **Amazon.ae** — تسجيل بائع رسمي. عمولة فئة الجمال من صفحتهم: 8% للمنتج ≤ 50 درهم و15% للأعلى (حد أدنى 1 درهم)، حساب Professional بلا اشتراك شهري «لفترة محدودة» (قُرئت 9/10/2026).");
L.push('- **Tradeling** — رابط تسجيل بائع رسمي يعمل؛ فئة التجميل غير مذكورة ضمن فئاتهم، والعمولة بلا أرقام.');
L.push('- **Begad** — تسجيل بائع رسمي: رخصة + إثبات بنك + هوية؛ «تسجيل مجاني»، عمولة ثابتة لكل فئة بلا أرقام. تواصل: sellers@begad.ae.');
L.push('- **noon** — الموقع يحجب الفحص الآلي (403)؛ لم يُتجاوز. التأكيد يدوي.');
L.push('- **LOOKFANTASTIC UAE** — صفحة موردين رسمية، تواصل partnerships@thehutgroup.com.');
L.push('- **Xpressions Style** — برنامج Business Network (تجزئة/جملة/توزيع)، تواصل business.development@xpressionsstyle.com.');
L.push('- **Mumzworld** — نموذج تقديم علامات (~7 أيام)، لكن تخصصه أم/طفل.');
L.push('- **المتاجر والصيدليات الكبرى** (Watsons، Faces، Boots، Life، myAster…): الموقع يعمل، لا تسجيل بائع ذاتي، ولم تظهر صفحة موردين ← اتفاق توريد مع المشتريات (غير مؤكد).', '');
L.push('## القيود', '');
L.push('- مواقع كثيرة تحجب الفحص الآلي (Cloudflare/403): لم تُتجاوز، وسُجلت «غير مؤكدة».');
L.push('- أرقام العمولات المنشورة بمدونات (مثل نطاق noon) غير معتمدة هنا.');
L.push('- روابط في التوسّع أخطأت النطاق (WeMENA وGo To Beauty) فاستُبعدت بدل اختلاق روابط بديلة.');
L.push("- تسجيل الشركة (جاهز 100%) ≠ تسجيل المنتجات (Montaji — يحتاج تحققاً) ≠ شروط كل منصة. لا شيء هنا يضمن قبول LOWE'S.");
L.push('- البحث بلا Firecrawl: بحث ويب عام + صفحات رسمية + أدلة منشورة.', '');
L.push('## الملفات', '');
L.push('- `LOWES_UAE_Sales_Platforms_Verified_2026-10-09.xlsx` (5 أوراق)', '- `uae_sales_platforms_2026-10-09.json` و`.csv`', '- `uae_sales_platforms_excluded_2026-10-09.csv` (المستبعد وأسبابه)', '- السكربتات: `scripts/b2b/discovery/audit_platforms.cjs` و`build_platform_db.cjs` و`platform_annotations_2026-10-09.json`');
fs.writeFileSync(dir + '/UAE_Sales_Platforms_Report_2026-10-09.md', L.join('\n'));
console.log('report written');
