// Writes the Markdown report for the sales-platform research from the data (all numbers are computed, none typed by hand).
// usage: node write_platform_report.cjs <platformsDir> [baseCommit]
const fs = require('fs');
const { execSync } = require('child_process');
const dir = process.argv[2];
const BASE = process.argv[3] || '68c97b5';
const j = JSON.parse(fs.readFileSync(dir + '/uae_sales_platforms_2026-10-09.json', 'utf8'));
const s = j.stats, rows = j.rows;
const ov = JSON.parse(fs.readFileSync(dir + '/overlap_map_with_leads_batches_2026-10-09.json', 'utf8')).matches;
let baseNames = new Set();
try {
  const rel = 'data/b2b/uae/platforms_2026-10-09/uae_sales_platforms_2026-10-09.json';
  const old = JSON.parse(execSync(`git show ${BASE}:${rel}`, { cwd: dir + '/../../../..', maxBuffer: 1 << 28 }).toString('utf8'));
  baseNames = new Set(old.rows.map((r) => r.name.toLowerCase()));
} catch (e) { console.log('base commit not readable:', String(e.message).slice(0, 80)); }
const isNew = (r) => !baseNames.has(r.name.toLowerCase());
const newRows = rows.filter(isNew);
const dups = j.excluded.filter((e) => e.kind === 'duplicate').length;
const esc = (x) => String(x ?? '').replace(/\|/g, ';').replace(/\n/g, ' ');
const L = [];
L.push('# تقرير بحث منصات البيع بالإمارات — المرحلة 3 (9 تشرين الأول 2026)', '');
L.push("> مصادر عامة فقط. لا Import، لا قاعدة بيانات، لا Merge، لا Deploy. المجهول = «غير معروف». لا عمولات ولا شروط إلا من صفحة رسمية قُرئت مع رابطها. **البحث غير مكتمل** — الأعداد أدناه لا تدل على اكتماله (انظر «ما تبقى»).", '');
L.push('## الأعداد الفعلية', '', '| البند | العدد |', '|---|---|');
L.push(`| جهات فُحصت إجمالاً (51 من ملف حسام + ${s.input_records - 51} مكتشفة) | ${s.input_records} |`);
L.push(`| بعد التنظيف (مكررات ${dups} + مستبعدة ${s.excluded_total - dups}) | **${s.kept}** |`);
L.push(`| جديدة بعد إزالة التكرار عن commit \`${BASE}\` (165 جهة) | **${newRows.length}** |`);
L.push(`| **متحقق منها فعلياً** (الموقع يستجيب ويظهر فيه ما يدل على الإمارات أو صفحة رسمية قُرئت) | **${s.verified_actually}** |`);
L.push(`| **تسجيل بائع مباشر مؤكد من صفحة رسمية** (فئة A) | **${s.tiers.A}** — منها Lets Tango بأولوية منخفضة |`);
L.push(`| **مناسبة لتقديم LOWE'S كمورد** (B توزيع/جملة + C اتفاق مورد) | **${s.suitable_as_supplier_B_C}** (B=${s.tiers.B}، C=${s.tiers.C}) — «مناسبة» تعني قناة محتملة، لا قبولاً مؤكداً |`);
L.push(`| **لم يتحدد وضعها** (فئة D) | **${s.undetermined_D}** |`);
L.push(`| غير مناسبة (E داخل السجلات) + مستبعدة بسجل منفصل | ${s.tiers.E_in_rows} + ${s.tiers.E_excluded_list} |`);
L.push(`| تحجب الفحص الآلي ولم تُتجاوز | ${s.protected_not_verified} |`);
L.push(`| لم تستجب عند الفحص (لا يعني أنها غير موجودة) | ${s.unreachable} |`);
L.push(`| روابط تحتاج مراجعة يدوية | ${s.manual_review} |`);
L.push(`| رسوم رسمية معلنة / شروط ترخيص رسمية / شروط تسجيل منتج رسمية | ${s.with_official_fee_source} / ${s.with_license_req_source} / ${s.with_product_reg_source} |`);
L.push(`| جهات خضعت لمراجعة يدوية مسبّبة (سبب ومصدر وتاريخ لكل منها) | ${s.reviewed_manually} |`, '');
L.push('### التصنيف النهائي', '', '| التصنيف | العدد |', '|---|---|');
Object.entries(s.by_classification).sort((a, b) => b[1] - a[1]).forEach(([k, v]) => L.push(`| ${k} | ${v} |`));
L.push('', '## أفضل 20 جهة للبدء بالتسجيل أو التواصل', '');
L.push('| # | الجهة | التصنيف | سبب الترتيب | الرابط | تواصل منشور | رسوم رسمية |', '|---|---|---|---|---|---|---|');
j.start_list.map((n) => rows.find((r) => r.name === n)).filter(Boolean).forEach((r, i) => L.push(`| ${i + 1} | ${esc(r.name)} | ${esc(r.classification)} | ${esc(r.start_reason || r.tier_reason)} | ${esc(r.seller_registration_url || r.supplier_or_partnership_url || r.official_website)} | ${esc(r.public_business_contact)} | ${esc(r.fees_source ? r.fees_commissions : 'غير معروف')} |`));
L.push('', '## فحص منصات التسجيل المباشر (فئة A) — لا يوجد «جاهز للبيع» قبل هذه الشروط', '');
L.push('| المنصة | نموذج تسجيل بائع | قبول فئة التجميل | أهلية شركة LOWE\'S الإماراتية | شروط الإدراج | مستندات/موافقات/رسوم معلنة |', '|---|---|---|---|---|---|');
L.push('| Amazon.ae | نعم (sellercentral.amazon.ae) | «Beauty» بلا قيود لكن **topicals تتطلب موافقة**؛ Beauty Topicals وCosmetics & Skin/Hair Care مقيّدة (صفحات القيود لم تُقرأ) | الصفحة: «Dubai Trade Licence» أو سجل تجاري؛ **المنطقة الحرة غير منصوصة** — يُتحقق | GTIN/موافقات المنتج: غير منصوصة | هوية، كشف بنكي/خدمات، سجل تجاري أو توكيل، حساب بنكي. عمولة الجمال 8% (≤ 50 درهم) و15% (> 50)، حد أدنى 1 درهم، بدون VAT |');
L.push('| Begad | نعم | «Beauty» فئة شائعة؛ العناية بالبشرة غير منصوصة | رخصة تجارية (نوعها غير منصوص) | غير منصوصة | رخصة + إثبات بنك + هوية؛ تسجيل مجاني؛ العمولة «ثابتة لكل فئة» بلا أرقام |');
L.push('| K Beauty Souq | نموذج تاجر للمراجعة | سوق K-beauty (28 علامة كورية)؛ علامات غير كورية غير منصوصة | الرخصة اختيارية بالنموذج | غير منصوصة | العمولة والشروط غير معلنة |');
L.push('| Tradeling | نعم (B2B) | **لا تظهر فئة تجميل** بين فئاتهم | غير منصوص | غير منصوصة | عنوان «Commission structure» بلا أرقام؛ دفع مرتين شهرياً |');
L.push('| Lets Tango | زر Start Selling | **فئات إلكترونيات؛ التجميل غير منصوص** → أولوية منخفضة | غير منصوص | غير منصوصة | غير معلنة |');
L.push('', '## التداخل مع دفعات ليدز المتاجر 1-3 (مطابقة فقط، بلا حذف)', '');
const byRole = ov.reduce((m, o) => ((m[o.platform_role] = (m[o.platform_role] || 0) + 1), m), {});
L.push(`${ov.length} مطابقة (بالموقع أو الاسم) — الملف: \`overlap_map_with_leads_batches_2026-10-09.csv\`. توزيع الدور: ${Object.entries(byRole).map(([k, v]) => `${k}: ${v}`).join(' · ')}.`);
L.push('القاعدة: سجل الليدز = جهة قد تشتري/تبيع (عميل أو موزع محتمل)؛ سجل المنصات = **قناة/مسار** بيع أو توريد. جهة واحدة قد تظهر بالقاعدتين بلا تعارض ولا تُدمج السجلات.', '');
L.push('## المنهجية', '');
L.push('1. فحص آلي لكل رابط (حالة HTTP، العنوان، إشارات الإمارات، روابط البائع/المورد)، وإعادة فحص الجهات التي لم تستجب بروابط بديلة ومهلة أطول.');
L.push('2. مراجعة نصوص الصفحات الرسمية يدوياً (WebFetch) قبل اعتماد أي مسار بيع أو رسم أو شرط، وكل قرار تصنيف يحمل **سببه ومصدره وتاريخه** في الملفات.');
L.push('3. التوسّع: بحث ويب عام بالعربية والإنجليزية، مقالات وأدلة منشورة وروابطها الخارجية، ملفات عارضي Beautyworld، وصفحات رسمية. DuckDuckGo أعاد تحدّياً أمنياً بعد استعلامين فتوقفتُ دون تجاوز.');
L.push('4. إزالة التكرار بالاسم والنطاق عبر كل الدفعات. روابط مخمَّنة لم تستجب لا تُنشر كروابط رسمية (تُحفظ في `url_guess_not_verified`).', '');
L.push('## القيود', '');
L.push('- مواقع كثيرة تحجب الفحص الآلي (Cloudflare/403/401) أو تنتهي مهلتها ولم أتجاوزها؛ صُنفت «غير مؤكدة» لا «غير نشطة».');
L.push('- عمولات المدونات (noon 4–27%، Lets Tango 10%، Cobone 15%) **غير معتمدة**.');
L.push('- لا مصدر رسمي لشروط تسجيل المنتجات (Montaji/وزارة الصحة) لأي منصة.');
L.push("- تسجيل الشركة (جاهز 100%) ≠ تسجيل المنتجات ≠ شروط كل منصة؛ لا شيء هنا يضمن قبول LOWE'S، ولم أتحقق من أهلية رخصة المنطقة الحرة لدى أي منصة.");
L.push('- قائمة عارضي Beautyworld Dubai 2026 الرسمية صفحة JavaScript لا تُقرأ آلياً؛ أُخذت أسماء من ملفات عارضين فرعية ومقالات فقط.', '');
L.push('## ما تبقى (البحث غير مكتمل)', '');
L.push('- فتح روابط `uae_sales_platforms_manual_review_2026-10-09.csv` يدوياً (الجهات المحجوبة وغير المستجيبة)، وأهمها noon وTrendyol وSephora وLulu.');
L.push('- اكتشاف مزيد من المتاجر المستقلة في عجمان ورأس الخيمة والفجيرة وأم القيوين والعين (النتائج المنشورة قليلة وأغلبها عبر talabat بلا موقع خاص).');
L.push('- مسارات موردين لسلاسل الصيدليات والمتاجر الكبرى بالتواصل المباشر مع المشتريات.');
L.push('- قراءة نماذج Union Coop (PDF) واتفاقية سوقها، وصفحات قيود Amazon للعناية الموضعية.', '');
L.push('## الملفات', '');
['LOWES_UAE_Sales_Platforms_Verified_2026-10-09.xlsx (9 أوراق: الكل، A/B/C/D/E، قائمة البدء، مراجعة يدوية)', 'uae_sales_platforms_2026-10-09.json و.csv', 'uae_sales_platforms_excluded_2026-10-09.csv', 'uae_sales_platforms_manual_review_2026-10-09.csv', 'uae_sales_platforms_start_list_2026-10-09.csv', 'overlap_map_with_leads_batches_2026-10-09.csv و.json', 'audit_raw/ (نتائج الفحص الخام لكل الدفعات)'].forEach((x) => L.push(`- \`${x}\``));
fs.writeFileSync(dir + '/UAE_Sales_Platforms_Report_2026-10-09.md', L.join('\n'));
console.log('report written; new vs base:', newRows.length, '| top20', j.start_list.length);
